# This workflow runs nighly builds for each package.
name: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      pkgs: ${{ steps.matrix.outputs.pkgs }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Matrix
        id: matrix
        uses: actions/github-script@v7
        env:
          DISABLED_PACKAGES: credential-helpers,model,scan,sbom
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const disabledPkgs = (process.env.DISABLED_PACKAGES || '').split(',').map(s => s.trim()).filter(Boolean);
            const pkgs = fs.readdirSync('./pkg', { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name).filter(name => !disabledPkgs.includes(name));
            core.info(JSON.stringify(pkgs, null, 2));
            core.setOutput('pkgs', JSON.stringify(pkgs));

  build:
    uses: ./.github/workflows/.build.yml
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJson(needs.prepare.outputs.pkgs) }}
    with:
      name: ${{ matrix.pkg }}
      push: true
      envs: |
        NIGHTLY_BUILD=1
    secrets: inherit
